name: anonytix-web
region: fra

static_sites:
  - name: web
    github:
      repo: IliasAlmerekov/anonytix-web
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: dist
    catchall_document: index.html
    routes:
      - path: /
